/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;
import controllers.ClienteController;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import models.ClienteModel;

/**
 *
 * @author crist
 */
public class Clientes extends javax.swing.JPanel {

    //CREACION DE VARIABLES
    ClienteController clienteController;
    ClienteModel cliente;
    
    /**
     * Creates new form Principal
     */
    public Clientes() {
        clienteController = new ClienteController();
        FlatLightLaf.install();
        initComponents();
        InitStyles();  
        LoadClientes();
        setJTexFieldChanged(this.cedulaClienteConsultaTxt);        
    }        
    
    private void InitStyles(){
        lbl1.putClientProperty("FlatLaf.styleClass", "large");
        lbl1.setForeground(Color.black);
        lbl2.putClientProperty("FlatLaf.styleClass", "large");
        lbl2.setForeground(Color.black);
        lbl3.putClientProperty("FlatLaf.styleClass", "large");
        lbl3.setForeground(Color.black);
        lbl4.putClientProperty("FlatLaf.styleClass", "large");
        lbl4.setForeground(Color.black);
        lbl5.putClientProperty("FlatLaf.styleClass", "large");
        lbl5.setForeground(Color.black);
        lbl6.putClientProperty("FlatLaf.styleClass", "large");
        lbl6.setForeground(Color.black);
        lbl7.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl7.setForeground(Color.black);
        lbl8.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl8.setForeground(Color.black);
        lbl9.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl9.setForeground(Color.black);
        lbl10.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl10.setForeground(Color.black);        
        titleLbl.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        titleLbl.setForeground(Color.black);
    }

    private void LoadClientes(){                       
        DefaultTableModel tabla =  (DefaultTableModel) clientesTbl.getModel();       
        tabla.setRowCount(0);
        clienteController.findAll().forEach((u) -> tabla.addRow(new Object[] {u.getId(), u.getCedula(), u.getNombre(), u.getMembresia(), u.getCorreo(), u.getCelular()}));        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        bg = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        cedulaClienteTxt = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesTbl = new javax.swing.JTable();
        titleLbl = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        crearClienteBtn = new javax.swing.JButton();
        consultarClienteBtn = new javax.swing.JButton();
        nombreClienteTxt = new javax.swing.JTextField();
        correoClienteTxt = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        celularClienteTxt = new javax.swing.JTextField();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        membresiaLbl = new javax.swing.JLabel();
        correoLbl = new javax.swing.JLabel();
        celularLbl = new javax.swing.JLabel();
        cedulaClienteConsultaTxt = new javax.swing.JTextField();
        editarClienteBtn = new javax.swing.JButton();
        eliminarClienteBtn = new javax.swing.JButton();
        membresiaClienteCbx = new javax.swing.JComboBox<>();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setPreferredSize(new java.awt.Dimension(715, 482));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        lbl3.setBackground(new java.awt.Color(0, 0, 0));
        lbl3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 0));
        lbl3.setText("Membresía:");

        lbl1.setBackground(new java.awt.Color(0, 0, 0));
        lbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Cedula Cliente:");

        cedulaClienteTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cedulaClienteTxt.setForeground(new java.awt.Color(0, 0, 0));

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Nombre Cliente:");

        lbl4.setBackground(new java.awt.Color(0, 0, 0));
        lbl4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 0, 0));
        lbl4.setText("Correo:");

        clientesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cedula", "Nombre", "Membresia", "Correo", "Celular"
            }
        ));
        jScrollPane1.setViewportView(clientesTbl);

        titleLbl.setBackground(new java.awt.Color(0, 0, 0));
        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Consulta");

        lbl6.setBackground(new java.awt.Color(0, 0, 0));
        lbl6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(0, 0, 0));
        lbl6.setText("Identificación:");

        lbl7.setBackground(new java.awt.Color(0, 0, 0));
        lbl7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl7.setForeground(new java.awt.Color(0, 0, 0));
        lbl7.setText("Nombre:");

        nombreLbl.setBackground(new java.awt.Color(0, 0, 0));
        nombreLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreLbl.setForeground(new java.awt.Color(0, 0, 0));

        crearClienteBtn.setBackground(new java.awt.Color(18, 90, 173));
        crearClienteBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        crearClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearClienteBtn.setText("Agregar");
        crearClienteBtn.setBorderPainted(false);
        crearClienteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteBtnActionPerformed(evt);
            }
        });

        consultarClienteBtn.setBackground(new java.awt.Color(18, 90, 173));
        consultarClienteBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        consultarClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        consultarClienteBtn.setText("Consultar");
        consultarClienteBtn.setBorderPainted(false);
        consultarClienteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClienteBtnActionPerformed(evt);
            }
        });

        nombreClienteTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreClienteTxt.setForeground(new java.awt.Color(0, 0, 0));

        correoClienteTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        correoClienteTxt.setForeground(new java.awt.Color(0, 0, 0));

        lbl5.setBackground(new java.awt.Color(0, 0, 0));
        lbl5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl5.setForeground(new java.awt.Color(0, 0, 0));
        lbl5.setText("Celular:");

        celularClienteTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        celularClienteTxt.setForeground(new java.awt.Color(0, 0, 0));

        lbl8.setBackground(new java.awt.Color(0, 0, 0));
        lbl8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl8.setForeground(new java.awt.Color(0, 0, 0));
        lbl8.setText("Membresía:");

        lbl9.setBackground(new java.awt.Color(0, 0, 0));
        lbl9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(0, 0, 0));
        lbl9.setText("Correo:");

        lbl10.setBackground(new java.awt.Color(0, 0, 0));
        lbl10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(0, 0, 0));
        lbl10.setText("Celular:");

        membresiaLbl.setBackground(new java.awt.Color(0, 0, 0));
        membresiaLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        membresiaLbl.setForeground(new java.awt.Color(0, 0, 0));

        correoLbl.setBackground(new java.awt.Color(0, 0, 0));
        correoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        correoLbl.setForeground(new java.awt.Color(0, 0, 0));

        celularLbl.setBackground(new java.awt.Color(0, 0, 0));
        celularLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        celularLbl.setForeground(new java.awt.Color(0, 0, 0));

        cedulaClienteConsultaTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cedulaClienteConsultaTxt.setForeground(new java.awt.Color(0, 0, 0));

        editarClienteBtn.setBackground(new java.awt.Color(18, 90, 173));
        editarClienteBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editarClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        editarClienteBtn.setText("Editar");
        editarClienteBtn.setBorderPainted(false);
        editarClienteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClienteBtnActionPerformed(evt);
            }
        });

        eliminarClienteBtn.setBackground(new java.awt.Color(18, 90, 173));
        eliminarClienteBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        eliminarClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarClienteBtn.setText("Eliminar");
        eliminarClienteBtn.setBorderPainted(false);
        eliminarClienteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClienteBtnActionPerformed(evt);
            }
        });

        membresiaClienteCbx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        membresiaClienteCbx.setForeground(new java.awt.Color(0, 0, 0));
        membresiaClienteCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "VIP", "Frecuente", "General" }));
        membresiaClienteCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membresiaClienteCbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cedulaClienteConsultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(membresiaLbl))
                            .addComponent(lbl9)
                            .addComponent(correoLbl)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(celularLbl))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(consultarClienteBtn)
                                    .addComponent(nombreLbl)))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cedulaClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl2))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(membresiaClienteCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(lbl4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(correoClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(celularClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crearClienteBtn))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(editarClienteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarClienteBtn)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2)
                    .addComponent(lbl1)
                    .addComponent(nombreClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearClienteBtn))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(correoClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl5)
                    .addComponent(celularClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3)
                    .addComponent(membresiaClienteCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(titleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl6)
                            .addComponent(cedulaClienteConsultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultarClienteBtn)
                        .addGap(12, 12, 12)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl7)
                            .addComponent(nombreLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl8)
                            .addComponent(membresiaLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl10)
                            .addComponent(celularLbl))
                        .addGap(36, 36, 36)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editarClienteBtn)
                            .addComponent(eliminarClienteBtn))
                        .addContainerGap(127, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteBtnActionPerformed
        //VALIDACION DE NULOS
        if(cedulaClienteTxt.getText().equals("") || nombreClienteTxt.getText().equals("") || membresiaClienteCbx.getSelectedItem().toString().equals("") || correoClienteTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Complete Los Campos Necesarios");
        }else{
            //VALIDACION EXISTENCIA DE CLIENTE
            this.cliente = (ClienteModel) clienteController.findByCedula(cedulaClienteTxt.getText());
            if(this.cliente != null){
                JOptionPane.showMessageDialog(null, "Ya existe un cliente con la cedula " + cedulaClienteTxt.getText() + " \nVerifique Nuevamente");
                this.cliente = null;
            }else{
                this.cliente = new ClienteModel(cedulaClienteTxt.getText(), nombreClienteTxt.getText(), membresiaClienteCbx.getSelectedItem().toString(), correoClienteTxt.getText(), celularClienteTxt.getText());
                if(clienteController.create(this.cliente)){
                    
                    JOptionPane.showMessageDialog(null, "Cliente Agregado Exitosamente: \n"  + nombreClienteTxt.getText());
                    
                    cedulaClienteTxt.setText("");
                    nombreClienteTxt.setText("");
                    membresiaClienteCbx.setSelectedIndex(0);
                    correoClienteTxt.setText("");
                    celularClienteTxt.setText("");
                    
                    LoadClientes();
                    this.cliente = null;
                }else{
                    JOptionPane.showMessageDialog(null, "Cliente NO guardado, intente de nuevo: \n" + nombreClienteTxt.getText());
                    this.cliente = null;
                }
            }
        }
    }//GEN-LAST:event_crearClienteBtnActionPerformed

    private void consultarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarClienteBtnActionPerformed
        // TODO add your handling code here:
        cliente = (ClienteModel) clienteController.findByCedula(cedulaClienteConsultaTxt.getText());
        if(cliente != null){
            nombreLbl.setText(cliente.getNombre());
            membresiaLbl.setText(cliente.getMembresia());
            correoLbl.setText(cliente.getCorreo());
            celularLbl.setText(cliente.getCelular());
        }else{
            JOptionPane.showMessageDialog(null, "Cliente No Existente");
            cedulaClienteConsultaTxt.setText("");
            nombreLbl.setText("");
            membresiaLbl.setText("");
            correoLbl.setText("");
            celularLbl.setText("");            
        }
    }//GEN-LAST:event_consultarClienteBtnActionPerformed

    private void editarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClienteBtnActionPerformed
        // TODO add your handling code here:
        if(cliente == null){
            JOptionPane.showMessageDialog(null, "Consulte el Cliente a Editar");
        }else{
            EditarCliente c = new EditarCliente(this.cliente, this.clientesTbl);
            c.setVisible(true);
            LoadClientes();
        }  
        cedulaClienteConsultaTxt.setText("");
        nombreLbl.setText("");
        membresiaLbl.setText("");
        correoLbl.setText("");
        celularLbl.setText("");    
    }//GEN-LAST:event_editarClienteBtnActionPerformed

    private void eliminarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClienteBtnActionPerformed
        // TODO add your handling code here:
        if(cliente == null){
            JOptionPane.showMessageDialog(null, "Consulte el Cliente a Eliminar");
        }else{
            int confirmacion = JOptionPane.showConfirmDialog(null, "Desea eliminar el Cliente:\n" + cliente.getNombre());
            if(confirmacion == JOptionPane.YES_OPTION){
                if(clienteController.deleteByCedula(cliente.getCedula())){
                    JOptionPane.showMessageDialog(null, "Cliente Eliminado Correctamente");                       
                }
                cedulaClienteConsultaTxt.setText("");
                nombreLbl.setText("");
                membresiaLbl.setText("");
                correoLbl.setText("");
                celularLbl.setText("");    
            }else{
                JOptionPane.showMessageDialog(null, "El Cliente No Ha Sido Eliminado");                       
            }
        }
        LoadClientes();
    }//GEN-LAST:event_eliminarClienteBtnActionPerformed
    
    private void setJTexFieldChanged(JTextField txt){
        DocumentListener documentListener = new DocumentListener() {
 
        @Override
        public void changedUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void insertUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void removeUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
        };
        txt.getDocument().addDocumentListener(documentListener);
 
    } 
    private void printIt(DocumentEvent documentEvent) {
        DocumentEvent.EventType type = documentEvent.getType();
 
        if (type.equals(DocumentEvent.EventType.CHANGE))
        {
            
        }
        else if (type.equals(DocumentEvent.EventType.INSERT))
        {
           //Método a ejecutar            
        }
        else if (type.equals(DocumentEvent.EventType.REMOVE))
        {
            //Método a ejecutar
            nombreLbl.setText("");
            membresiaLbl.setText("");
            correoLbl.setText("");
            celularLbl.setText("");             
            this.cliente = null;
        }
    }
    
    private void membresiaClienteCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membresiaClienteCbxActionPerformed
        //NO LO USO NO SE QUITARLO
    }//GEN-LAST:event_membresiaClienteCbxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JTextField cedulaClienteConsultaTxt;
    private javax.swing.JTextField cedulaClienteTxt;
    private javax.swing.JTextField celularClienteTxt;
    private javax.swing.JLabel celularLbl;
    private javax.swing.JTable clientesTbl;
    private javax.swing.JButton consultarClienteBtn;
    private javax.swing.JTextField correoClienteTxt;
    private javax.swing.JLabel correoLbl;
    private javax.swing.JButton crearClienteBtn;
    private javax.swing.JButton editarClienteBtn;
    private javax.swing.JButton eliminarClienteBtn;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JComboBox<String> membresiaClienteCbx;
    private javax.swing.JLabel membresiaLbl;
    private javax.swing.JTextField nombreClienteTxt;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
