/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;
import controllers.EmpleadoController;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.EmpleadoModel;

/**
 *
 * @author crist
 */
public class EditarEmpleado extends javax.swing.JFrame {        
    
    EmpleadoController empleadoController;
    EmpleadoModel empleado;
    JTable empleadosTabla;
    
    /**
     * Creates new form AgregarCliente
     */
    public EditarEmpleado(EmpleadoModel e, JTable empleadosTbl) {
        initComponents();
        FlatLightLaf.install();
        InitStyles();        
        LoadEmpleado(e);             
        this.empleadosTabla = empleadosTbl;
        this.empleadoController = new EmpleadoController();
    }        
    
    private void InitStyles(){
        lbl1.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl1.setForeground(Color.black);
        lbl2.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl2.setForeground(Color.black);
        lbl3.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl3.setForeground(Color.black);
        lbl4.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl4.setForeground(Color.black);
        lbl5.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl5.setForeground(Color.black);
        lbl6.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl6.setForeground(Color.black);
        titleLbl.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        titleLbl.setForeground(Color.black);
    }
    
    private void LoadEmpleado(EmpleadoModel e){
        cedulaEmpleadoLbl.setText(e.getCedula());
        nombreEmpleadoTxt.setText(e.getNombre());
        int selectedIndex = cargoEmpleadoCbx.getItemCount() - 1;
        for(int i=0; i < cargoEmpleadoCbx.getItemCount(); i++){
            String item = cargoEmpleadoCbx.getItemAt(i);
            if(item.equals(e.getCargo())){
                selectedIndex = i;
                break;
            }
        }
        cargoEmpleadoCbx.setSelectedIndex(selectedIndex);
        correoEmpleadoTxt.setText(e.getCorreo());
        celularEmpleadoTxt.setText(e.getCelular());
        contraseñaEmpleadoTxt.setText(e.getContraseña());
    }
     
    private void LoadEmpleados(JTable empleadosTbl){                       
        DefaultTableModel tabla = (DefaultTableModel) empleadosTbl.getModel();       
        tabla.setRowCount(0);
        empleadoController.findAll().forEach((u) -> tabla.addRow(new Object[] {u.getId(), u.getCedula(), u.getNombre(), u.getCargo(), u.getCorreo(), u.getCelular(), u.getContraseña()}));        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        cedulaEmpleadoLbl = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        nombreEmpleadoTxt = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        cargoEmpleadoCbx = new javax.swing.JComboBox<>();
        lbl4 = new javax.swing.JLabel();
        correoEmpleadoTxt = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        celularEmpleadoTxt = new javax.swing.JTextField();
        editarEmpleadoBtn = new javax.swing.JButton();
        lbl6 = new javax.swing.JLabel();
        contraseñaEmpleadoTxt = new javax.swing.JTextField();

        setLocationByPlatform(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Edición de Empleados");

        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Cedula Empleado:");

        cedulaEmpleadoLbl.setForeground(new java.awt.Color(0, 0, 0));

        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Nombre Empleado:");

        lbl3.setForeground(new java.awt.Color(0, 0, 0));
        lbl3.setText("Cargo:");

        cargoEmpleadoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Administrador", "Developer" }));

        lbl4.setForeground(new java.awt.Color(0, 0, 0));
        lbl4.setText("Correo Empleado:");

        lbl5.setForeground(new java.awt.Color(0, 0, 0));
        lbl5.setText("Celular Empleado:");

        editarEmpleadoBtn.setBackground(new java.awt.Color(18, 90, 163));
        editarEmpleadoBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editarEmpleadoBtn.setForeground(new java.awt.Color(255, 255, 255));
        editarEmpleadoBtn.setText("Editar");
        editarEmpleadoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarEmpleadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEmpleadoBtnActionPerformed(evt);
            }
        });

        lbl6.setForeground(new java.awt.Color(0, 0, 0));
        lbl6.setText("Contraseña Empleado:");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(lbl1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cedulaEmpleadoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(lbl2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombreEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(lbl3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cargoEmpleadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(lbl4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(correoEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(lbl5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(celularEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contraseñaEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(editarEmpleadoBtn)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(cedulaEmpleadoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(nombreEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(cargoEmpleadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(correoEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5)
                    .addComponent(celularEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl6)
                    .addComponent(contraseñaEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editarEmpleadoBtn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarEmpleadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmpleadoBtnActionPerformed
        if(nombreEmpleadoTxt.getText().equals("") || cargoEmpleadoCbx.getSelectedItem().toString().equals("") || correoEmpleadoTxt.getText().equals("") || contraseñaEmpleadoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Complete Los Campos Necesarios");
        }else{
            empleado = new EmpleadoModel(cedulaEmpleadoLbl.getText(), nombreEmpleadoTxt.getText(), cargoEmpleadoCbx.getSelectedItem().toString(), correoEmpleadoTxt.getText(), celularEmpleadoTxt.getText(), contraseñaEmpleadoTxt.getText());
            if(empleadoController.update(empleado)){                        
                JOptionPane.showMessageDialog(null, "Empleado Editado Correctamente:\n" + this.empleado.getNombre());
                LoadEmpleados(this.empleadosTabla);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "El Empleado No Pudo Ser Editado");
                this.dispose();
            }            
        }        
    }//GEN-LAST:event_editarEmpleadoBtnActionPerformed
        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> cargoEmpleadoCbx;
    private javax.swing.JLabel cedulaEmpleadoLbl;
    private javax.swing.JTextField celularEmpleadoTxt;
    private javax.swing.JTextField contraseñaEmpleadoTxt;
    private javax.swing.JTextField correoEmpleadoTxt;
    private javax.swing.JButton editarEmpleadoBtn;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JTextField nombreEmpleadoTxt;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
