/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;
import controllers.EmpleadoController;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import models.EmpleadoModel;
import models.PersonaModel;

/**
 *
 * @author crist
 */
public class Empleados extends javax.swing.JPanel {

    //CREACION DE VARIABLES
    EmpleadoController empleadoController;  
    EmpleadoModel empleado;
    
    /**
     * Creates new form Principal
     */
    public Empleados() {
        empleadoController = new EmpleadoController();        
        FlatLightLaf.install();
        initComponents();
        InitStyles();  
        LoadEmpleados();
        setJTexFieldChanged(this.cedulaEmpleadoConsultaTxt);
    }
    
    private void InitStyles(){
        lbl1.putClientProperty("FlatLaf.styleClass", "large");
        lbl1.setForeground(Color.black);
        lbl2.putClientProperty("FlatLaf.styleClass", "large");
        lbl2.setForeground(Color.black);
        lbl3.putClientProperty("FlatLaf.styleClass", "large");
        lbl3.setForeground(Color.black);
        lbl4.putClientProperty("FlatLaf.styleClass", "large");
        lbl4.setForeground(Color.black);
        lbl5.putClientProperty("FlatLaf.styleClass", "large");
        lbl5.setForeground(Color.black);
        lbl6.putClientProperty("FlatLaf.styleClass", "large");
        lbl6.setForeground(Color.black);
        lbl7.putClientProperty("FlatLaf.styleClass", "large");
        lbl7.setForeground(Color.black);
        lbl8.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl8.setForeground(Color.black);
        lbl9.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl9.setForeground(Color.black);
        lbl10.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl10.setForeground(Color.black);        
        lbl11.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl11.setForeground(Color.black);   
        lbl12.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl12.setForeground(Color.black);   
        titleLbl.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        titleLbl.setForeground(Color.black);
    }

    private void LoadEmpleados(){                       
        DefaultTableModel tabla =  (DefaultTableModel) empleadosTbl.getModel();       
        tabla.setRowCount(0);
        empleadoController.findAll().forEach((u) -> tabla.addRow(new Object[] {u.getId(), u.getCedula(), u.getNombre(), u.getCargo(), u.getCorreo(), u.getCelular(), u.getContraseña()}));        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        bg = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        cargoEmpleadoCbx = new javax.swing.JComboBox<>();
        lbl1 = new javax.swing.JLabel();
        cedulaEmpleadoTxt = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empleadosTbl = new javax.swing.JTable();
        titleLbl = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        crearEmpleadoBtn = new javax.swing.JButton();
        consultarEmpleadoBtn = new javax.swing.JButton();
        nombreEmpleadoTxt = new javax.swing.JTextField();
        correoEmpleadoTxt = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        celularEmpleadoTxt = new javax.swing.JTextField();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        cargoLbl = new javax.swing.JLabel();
        correoLbl = new javax.swing.JLabel();
        celularLbl = new javax.swing.JLabel();
        cedulaEmpleadoConsultaTxt = new javax.swing.JTextField();
        editarEmpleadoBtn = new javax.swing.JButton();
        eliminarEmpleadoBtn = new javax.swing.JButton();
        lbl6 = new javax.swing.JLabel();
        contraseñaEmpleadoTxt = new javax.swing.JTextField();
        lbl12 = new javax.swing.JLabel();
        contraseñaLbl = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setPreferredSize(new java.awt.Dimension(715, 482));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        lbl3.setBackground(new java.awt.Color(0, 0, 0));
        lbl3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 0));
        lbl3.setText("Cargo:");

        cargoEmpleadoCbx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cargoEmpleadoCbx.setForeground(new java.awt.Color(0, 0, 0));
        cargoEmpleadoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Vendedor", "Administrador", "Developer" }));
        cargoEmpleadoCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoEmpleadoCbxActionPerformed(evt);
            }
        });

        lbl1.setBackground(new java.awt.Color(0, 0, 0));
        lbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Cedula Empleado:");

        cedulaEmpleadoTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cedulaEmpleadoTxt.setForeground(new java.awt.Color(0, 0, 0));

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Nombre Empleado:");

        lbl4.setBackground(new java.awt.Color(0, 0, 0));
        lbl4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 0, 0));
        lbl4.setText("Correo:");

        empleadosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cedula", "Nombre", "Cargo", "Correo", "Celular", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(empleadosTbl);

        titleLbl.setBackground(new java.awt.Color(0, 0, 0));
        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Consulta");

        lbl7.setBackground(new java.awt.Color(0, 0, 0));
        lbl7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl7.setForeground(new java.awt.Color(0, 0, 0));
        lbl7.setText("Cedula:");

        lbl8.setBackground(new java.awt.Color(0, 0, 0));
        lbl8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl8.setForeground(new java.awt.Color(0, 0, 0));
        lbl8.setText("Nombre:");

        nombreLbl.setBackground(new java.awt.Color(0, 0, 0));
        nombreLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreLbl.setForeground(new java.awt.Color(0, 0, 0));

        crearEmpleadoBtn.setBackground(new java.awt.Color(18, 90, 173));
        crearEmpleadoBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        crearEmpleadoBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearEmpleadoBtn.setText("Agregar");
        crearEmpleadoBtn.setBorderPainted(false);
        crearEmpleadoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearEmpleadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEmpleadoBtnActionPerformed(evt);
            }
        });

        consultarEmpleadoBtn.setBackground(new java.awt.Color(18, 90, 173));
        consultarEmpleadoBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        consultarEmpleadoBtn.setForeground(new java.awt.Color(255, 255, 255));
        consultarEmpleadoBtn.setText("Consultar");
        consultarEmpleadoBtn.setBorderPainted(false);
        consultarEmpleadoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarEmpleadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarEmpleadoBtnActionPerformed(evt);
            }
        });

        nombreEmpleadoTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreEmpleadoTxt.setForeground(new java.awt.Color(0, 0, 0));

        correoEmpleadoTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        correoEmpleadoTxt.setForeground(new java.awt.Color(0, 0, 0));

        lbl5.setBackground(new java.awt.Color(0, 0, 0));
        lbl5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl5.setForeground(new java.awt.Color(0, 0, 0));
        lbl5.setText("Celular:");

        celularEmpleadoTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        celularEmpleadoTxt.setForeground(new java.awt.Color(0, 0, 0));

        lbl9.setBackground(new java.awt.Color(0, 0, 0));
        lbl9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(0, 0, 0));
        lbl9.setText("Cargo:");

        lbl10.setBackground(new java.awt.Color(0, 0, 0));
        lbl10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(0, 0, 0));
        lbl10.setText("Correo:");

        lbl11.setBackground(new java.awt.Color(0, 0, 0));
        lbl11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl11.setForeground(new java.awt.Color(0, 0, 0));
        lbl11.setText("Celular:");

        cargoLbl.setBackground(new java.awt.Color(0, 0, 0));
        cargoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cargoLbl.setForeground(new java.awt.Color(0, 0, 0));

        correoLbl.setBackground(new java.awt.Color(0, 0, 0));
        correoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        correoLbl.setForeground(new java.awt.Color(0, 0, 0));

        celularLbl.setBackground(new java.awt.Color(0, 0, 0));
        celularLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        celularLbl.setForeground(new java.awt.Color(0, 0, 0));

        cedulaEmpleadoConsultaTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cedulaEmpleadoConsultaTxt.setForeground(new java.awt.Color(0, 0, 0));
        cedulaEmpleadoConsultaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaEmpleadoConsultaTxtActionPerformed(evt);
            }
        });

        editarEmpleadoBtn.setBackground(new java.awt.Color(18, 90, 173));
        editarEmpleadoBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editarEmpleadoBtn.setForeground(new java.awt.Color(255, 255, 255));
        editarEmpleadoBtn.setText("Editar");
        editarEmpleadoBtn.setBorderPainted(false);
        editarEmpleadoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarEmpleadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEmpleadoBtnActionPerformed(evt);
            }
        });

        eliminarEmpleadoBtn.setBackground(new java.awt.Color(18, 90, 173));
        eliminarEmpleadoBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        eliminarEmpleadoBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarEmpleadoBtn.setText("Eliminar");
        eliminarEmpleadoBtn.setBorderPainted(false);
        eliminarEmpleadoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarEmpleadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpleadoBtnActionPerformed(evt);
            }
        });

        lbl6.setBackground(new java.awt.Color(0, 0, 0));
        lbl6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(0, 0, 0));
        lbl6.setText("Contraseña:");

        contraseñaEmpleadoTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contraseñaEmpleadoTxt.setForeground(new java.awt.Color(0, 0, 0));

        lbl12.setBackground(new java.awt.Color(0, 0, 0));
        lbl12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl12.setForeground(new java.awt.Color(0, 0, 0));
        lbl12.setText("Contraseña:");

        contraseñaLbl.setBackground(new java.awt.Color(0, 0, 0));
        contraseñaLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contraseñaLbl.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cedulaEmpleadoConsultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl10)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contraseñaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(consultarEmpleadoBtn)
                                    .addComponent(nombreLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(correoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cedulaEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl2)
                        .addGap(16, 16, 16)
                        .addComponent(nombreEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(crearEmpleadoBtn))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargoEmpleadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correoEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(celularEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contraseñaEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(editarEmpleadoBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eliminarEmpleadoBtn))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lbl11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(celularLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2)
                    .addComponent(lbl1)
                    .addComponent(nombreEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearEmpleadoBtn))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargoEmpleadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4)
                    .addComponent(correoEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl5)
                    .addComponent(celularEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3)
                    .addComponent(lbl6)
                    .addComponent(contraseñaEmpleadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(titleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl7)
                            .addComponent(cedulaEmpleadoConsultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultarEmpleadoBtn)
                        .addGap(12, 12, 12)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl8)
                            .addComponent(nombreLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl9)
                            .addComponent(cargoLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl11)
                            .addComponent(celularLbl))
                        .addGap(5, 5, 5)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl12)
                            .addComponent(contraseñaLbl))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editarEmpleadoBtn)
                            .addComponent(eliminarEmpleadoBtn))
                        .addContainerGap(131, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargoEmpleadoCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoEmpleadoCbxActionPerformed
        //NO LO USO NO SE QUITARLO
    }//GEN-LAST:event_cargoEmpleadoCbxActionPerformed

    private void crearEmpleadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEmpleadoBtnActionPerformed
        //VALIDACION DE NULOS
        if(cedulaEmpleadoTxt.getText().equals("") || nombreEmpleadoTxt.getText().equals("") || cargoEmpleadoCbx.getSelectedItem().toString().equals("") || correoEmpleadoTxt.getText().equals("") || contraseñaEmpleadoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Complete Los Campos Necesarios");
        }else{
            //VALIDACION DE EXISTENCIA DE EMPLEADO
            this.empleado = (EmpleadoModel) empleadoController.findByCedula(cedulaEmpleadoTxt.getText());
            if(this.empleado != null){
                JOptionPane.showMessageDialog(null, "Ya existe un empleado con la cedula " + cedulaEmpleadoTxt.getText() + " \nVerifique Nuevamente");
                this.empleado = null;
            }else{
                this.empleado = new EmpleadoModel(cedulaEmpleadoTxt.getText(), nombreEmpleadoTxt.getText(), cargoEmpleadoCbx.getSelectedItem().toString(), correoEmpleadoTxt.getText(), celularEmpleadoTxt.getText(), contraseñaEmpleadoTxt.getText());
                if(empleadoController.create(empleado)){
                    
                    JOptionPane.showMessageDialog(null, "Empleado Agregado Exitosamente: \n"  + nombreEmpleadoTxt.getText());
                    
                    cedulaEmpleadoTxt.setText("");
                    nombreEmpleadoTxt.setText("");
                    cargoEmpleadoCbx.setSelectedIndex(0);
                    correoEmpleadoTxt.setText("");
                    celularEmpleadoTxt.setText("");
                    contraseñaEmpleadoTxt.setText("");
                                        
                    
                    LoadEmpleados();
                    this.empleado = null;
                }else{
                    JOptionPane.showMessageDialog(null, "Empleado NO guardado, intente de nuevo: \n" + nombreEmpleadoTxt.getText());
                    this.empleado = null;
                }                    
            }
        }
        
    }//GEN-LAST:event_crearEmpleadoBtnActionPerformed

    private void consultarEmpleadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarEmpleadoBtnActionPerformed
        // TODO add your handling code here:
        empleado = (EmpleadoModel) empleadoController.findByCedula(cedulaEmpleadoConsultaTxt.getText());
        if(empleado != null){
            nombreLbl.setText(empleado.getNombre());
            cargoLbl.setText(empleado.getCargo());
            correoLbl.setText(empleado.getCorreo());
            celularLbl.setText(empleado.getCelular());
            contraseñaLbl.setText(empleado.getContraseña());
        }else{
            JOptionPane.showMessageDialog(null, "Empleado No Existente");
            cedulaEmpleadoConsultaTxt.setText("");
            nombreLbl.setText("");
            cargoLbl.setText("");
            correoLbl.setText("");
            celularLbl.setText("");
            contraseñaLbl.setText("");
        }                
    }//GEN-LAST:event_consultarEmpleadoBtnActionPerformed

    private void editarEmpleadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmpleadoBtnActionPerformed
        if(empleado == null){
            JOptionPane.showMessageDialog(null, "Consulte el Empleado a Editar");
        }else{
            EditarEmpleado c = new EditarEmpleado(this.empleado, this.empleadosTbl);
            c.setVisible(true);                  
            LoadEmpleados();            
        }              
        cedulaEmpleadoConsultaTxt.setText("");
        nombreLbl.setText("");
        cargoLbl.setText("");
        correoLbl.setText("");
        celularLbl.setText("");
        contraseñaLbl.setText("");
    }//GEN-LAST:event_editarEmpleadoBtnActionPerformed

    private void eliminarEmpleadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpleadoBtnActionPerformed
        // TODO add your handling code here:
        if(empleado == null){
            JOptionPane.showMessageDialog(null, "Consulte el Empleado a Eliminar");
        }else{
            int confirmacion = JOptionPane.showConfirmDialog(null, "Desea eliminar el Empleado:\n" + empleado.getNombre());
            if(confirmacion == JOptionPane.YES_OPTION){
                if(empleadoController.deleteByCedula(empleado.getCedula())){
                    JOptionPane.showMessageDialog(null, "Empleado Eliminado Correctamente");                       
                }
                cedulaEmpleadoConsultaTxt.setText("");
                nombreLbl.setText("");
                cargoLbl.setText("");
                correoLbl.setText("");
                celularLbl.setText("");
                contraseñaLbl.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "El Empleado No Ha Sido Eliminado");                       
            }
        }
        LoadEmpleados();
    }//GEN-LAST:event_eliminarEmpleadoBtnActionPerformed

    //BORRAR Labels SI SE BORRA TEXTO
    private void setJTexFieldChanged(JTextField txt){
        DocumentListener documentListener = new DocumentListener() {
 
        @Override
        public void changedUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void insertUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void removeUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
        };
        txt.getDocument().addDocumentListener(documentListener);
 
    } 
    private void printIt(DocumentEvent documentEvent) {
        DocumentEvent.EventType type = documentEvent.getType();
 
        if (type.equals(DocumentEvent.EventType.CHANGE))
        {
            
        }
        else if (type.equals(DocumentEvent.EventType.INSERT))
        {
           //Método a ejecutar            
        }
        else if (type.equals(DocumentEvent.EventType.REMOVE))
        {
            //Método a ejecutar
            nombreLbl.setText("");
            cargoLbl.setText("");
            correoLbl.setText("");
            celularLbl.setText("");
            contraseñaLbl.setText("");
            this.empleado = null;
        }
    }
    
    private void cedulaEmpleadoConsultaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaEmpleadoConsultaTxtActionPerformed
        //YA NO LO USO PERO NO SE QUITARLO       
    }//GEN-LAST:event_cedulaEmpleadoConsultaTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> cargoEmpleadoCbx;
    private javax.swing.JLabel cargoLbl;
    private javax.swing.JTextField cedulaEmpleadoConsultaTxt;
    private javax.swing.JTextField cedulaEmpleadoTxt;
    private javax.swing.JTextField celularEmpleadoTxt;
    private javax.swing.JLabel celularLbl;
    private javax.swing.JButton consultarEmpleadoBtn;
    private javax.swing.JTextField contraseñaEmpleadoTxt;
    private javax.swing.JLabel contraseñaLbl;
    private javax.swing.JTextField correoEmpleadoTxt;
    private javax.swing.JLabel correoLbl;
    private javax.swing.JButton crearEmpleadoBtn;
    private javax.swing.JButton editarEmpleadoBtn;
    private javax.swing.JButton eliminarEmpleadoBtn;
    private javax.swing.JTable empleadosTbl;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JTextField nombreEmpleadoTxt;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
