/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import controllers.EmpleadoController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.UIManager;
import models.EmpleadoModel;

/**
 *
 * @author crist
 */
public class Inicio extends javax.swing.JFrame {

    //CREACION DE VARIABLES
    String cedula; 
    EmpleadoController empleadoController;
    EmpleadoModel empleado;
                
    /**
     * Creates new form Inicio
     */
    public Inicio(String Cedula){
        this.cedula = Cedula;
        empleadoController = new EmpleadoController();
        empleado = (EmpleadoModel) empleadoController.findByCedula(this.cedula);
        FlatLightLaf.install();
        initComponents();
        InitStyles();
        setDate();    
        InitContent();
    }
    
    //METODOS PROPIOS
    private void InitStyles(){                
        mensaje.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        mensaje.setForeground(Color.black);
        navtext.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        navtext.setForeground(Color.white);
        datetext.putClientProperty("FlatLaf.style", "font: 24 $light.font");
        datetext.setForeground(Color.white);
        title.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        title.setForeground(Color.white);                                   
    }    
    
    private void setDate(){
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        datetext.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));                
        String usuario = this.empleado.getNombre().substring(0,1).toUpperCase() + this.empleado.getNombre().substring(1);
        mensaje.setText("Bienvenido Nuevamente " + usuario);
    }       

    private void InitContent(){        
        Principal p1 = new Principal();
        p1.setSize(750,430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
        Color color = new Color(21,101,192);                
        principalBtn.setBackground(Color.white);
        principalBtn.setForeground(Color.black);
        ventasBtn.setBackground(color);
        ventasBtn.setForeground(Color.white);
        clientesBtn.setBackground(color);
        clientesBtn.setForeground(Color.white);        
        inventarioBtn.setBackground(color);
        inventarioBtn.setForeground(Color.white);
        if(empleado.getCargo().equals("Administrador") || empleado.getCargo().equals("Developer")){
            empleadosBtn.setBackground(color);
            empleadosBtn.setForeground(Color.white);            
        }else{
            System.out.println("El empleado es: " + empleado.getCargo());
            empleadosBtn.setVisible(false);
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menus = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        principalBtn = new javax.swing.JButton();
        ventasBtn = new javax.swing.JButton();
        clientesBtn = new javax.swing.JButton();
        empleadosBtn = new javax.swing.JButton();
        inventarioBtn = new javax.swing.JButton();
        cerrarSesionBtn = new javax.swing.JButton();
        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        navtext = new javax.swing.JLabel();
        datetext = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1032, 640));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menus.setBackground(new java.awt.Color(13, 71, 161));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Library Code");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        principalBtn.setBackground(new java.awt.Color(21, 101, 192));
        principalBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        principalBtn.setForeground(new java.awt.Color(255, 255, 255));
        principalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/casa.png"))); // NOI18N
        principalBtn.setText("Principal");
        principalBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        principalBtn.setBorderPainted(false);
        principalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        principalBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        principalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalBtnActionPerformed(evt);
            }
        });

        ventasBtn.setBackground(new java.awt.Color(21, 101, 192));
        ventasBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ventasBtn.setForeground(new java.awt.Color(255, 255, 255));
        ventasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ventas.png"))); // NOI18N
        ventasBtn.setText("Ventas");
        ventasBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        ventasBtn.setBorderPainted(false);
        ventasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ventasBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ventasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasBtnActionPerformed(evt);
            }
        });

        clientesBtn.setBackground(new java.awt.Color(21, 101, 192));
        clientesBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clientesBtn.setForeground(new java.awt.Color(255, 255, 255));
        clientesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clientes.png"))); // NOI18N
        clientesBtn.setText("Clientes");
        clientesBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        clientesBtn.setBorderPainted(false);
        clientesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesBtnActionPerformed(evt);
            }
        });

        empleadosBtn.setBackground(new java.awt.Color(21, 101, 192));
        empleadosBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empleadosBtn.setForeground(new java.awt.Color(255, 255, 255));
        empleadosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/empleados.png"))); // NOI18N
        empleadosBtn.setText("Empleados");
        empleadosBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        empleadosBtn.setBorderPainted(false);
        empleadosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empleadosBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        empleadosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosBtnActionPerformed(evt);
            }
        });

        inventarioBtn.setBackground(new java.awt.Color(21, 101, 192));
        inventarioBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventarioBtn.setForeground(new java.awt.Color(255, 255, 255));
        inventarioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/inventario.png"))); // NOI18N
        inventarioBtn.setText("Inventario");
        inventarioBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        inventarioBtn.setBorderPainted(false);
        inventarioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventarioBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioBtnActionPerformed(evt);
            }
        });

        cerrarSesionBtn.setBackground(new java.awt.Color(21, 101, 192));
        cerrarSesionBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cerrarSesionBtn.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesionBtn.setText("Cerrar Sesión");
        cerrarSesionBtn.setToolTipText("");
        cerrarSesionBtn.setActionCommand("");
        cerrarSesionBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        cerrarSesionBtn.setBorderPainted(false);
        cerrarSesionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarSesionBtn.setHideActionText(true);
        cerrarSesionBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cerrarSesionBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menusLayout = new javax.swing.GroupLayout(menus);
        menus.setLayout(menusLayout);
        menusLayout.setHorizontalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(principalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(ventasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(inventarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(clientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(empleadosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(cerrarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menusLayout.setVerticalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(principalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ventasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inventarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(clientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(empleadosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(cerrarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(menus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        background.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(25, 118, 210));

        navtext.setText("Administración/Control Library Code");

        datetext.setText("Hoy es {dayname} {day} de {month} de {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navtext, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datetext, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navtext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datetext, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        mensaje.setText("Bienvenido Nuevamente {username}");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void principalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalBtnActionPerformed
        Principal p1 = new Principal();
        p1.setSize(750,430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
                
        Color color = new Color(21,101,192);                
        principalBtn.setBackground(Color.white);
        principalBtn.setForeground(Color.black);
        ventasBtn.setBackground(color);
        ventasBtn.setForeground(Color.white);
        clientesBtn.setBackground(color);
        clientesBtn.setForeground(Color.white);
        empleadosBtn.setBackground(color);
        empleadosBtn.setForeground(Color.white);
        inventarioBtn.setBackground(color);
        inventarioBtn.setForeground(Color.white);
    }//GEN-LAST:event_principalBtnActionPerformed

    private void ventasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasBtnActionPerformed
        Ventas p1 = new Ventas();
        p1.setSize(750,430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
        Color color = new Color(21,101,192);                
        principalBtn.setBackground(color);
        principalBtn.setForeground(Color.white);
        ventasBtn.setBackground(Color.white);
        ventasBtn.setForeground(Color.black);
        clientesBtn.setBackground(color);
        clientesBtn.setForeground(Color.white);
        empleadosBtn.setBackground(color);
        empleadosBtn.setForeground(Color.white);
        inventarioBtn.setBackground(color);
        inventarioBtn.setForeground(Color.white);
    }//GEN-LAST:event_ventasBtnActionPerformed

    private void clientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesBtnActionPerformed
        Clientes p1 = new Clientes();
        p1.setSize(750,430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
        Color color = new Color(21,101,192);                
        principalBtn.setBackground(color);
        principalBtn.setForeground(Color.white);
        ventasBtn.setBackground(color);
        ventasBtn.setForeground(Color.white);
        clientesBtn.setBackground(Color.white);
        clientesBtn.setForeground(Color.black);
        empleadosBtn.setBackground(color);
        empleadosBtn.setForeground(Color.white);
        inventarioBtn.setBackground(color);
        inventarioBtn.setForeground(Color.white);
    }//GEN-LAST:event_clientesBtnActionPerformed

    private void empleadosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosBtnActionPerformed
        Empleados p1 = new Empleados();
        p1.setSize(750,430);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        Color color = new Color(21,101,192);                
        principalBtn.setBackground(color);
        principalBtn.setForeground(Color.white);
        ventasBtn.setBackground(color);
        ventasBtn.setForeground(Color.white);
        clientesBtn.setBackground(color);
        clientesBtn.setForeground(Color.white);
        empleadosBtn.setBackground(Color.white);
        empleadosBtn.setForeground(Color.black);
        inventarioBtn.setBackground(color);
        inventarioBtn.setForeground(Color.white);              
        
    }//GEN-LAST:event_empleadosBtnActionPerformed

    private void inventarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioBtnActionPerformed
        Inventario p1 = new Inventario();
        p1.setSize(750,430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
        Color color = new Color(21,101,192);                
        principalBtn.setBackground(color);
        principalBtn.setForeground(Color.white);
        ventasBtn.setBackground(color);
        ventasBtn.setForeground(Color.white);
        clientesBtn.setBackground(color);
        clientesBtn.setForeground(Color.white);
        empleadosBtn.setBackground(color);
        empleadosBtn.setForeground(Color.white);
        inventarioBtn.setBackground(Color.white);
        inventarioBtn.setForeground(Color.black);
    }//GEN-LAST:event_inventarioBtnActionPerformed

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //this.setVisible(false);
        Login c = new Login();                
        c.setVisible(true);   
    }//GEN-LAST:event_cerrarSesionBtnActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton cerrarSesionBtn;
    private javax.swing.JButton clientesBtn;
    private javax.swing.JPanel content;
    private javax.swing.JLabel datetext;
    private javax.swing.JButton empleadosBtn;
    private javax.swing.JPanel header;
    private javax.swing.JButton inventarioBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel menus;
    private javax.swing.JLabel navtext;
    private javax.swing.JButton principalBtn;
    private javax.swing.JLabel title;
    private javax.swing.JButton ventasBtn;
    // End of variables declaration//GEN-END:variables
   
}
