/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;
import controllers.LibroController;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import models.LibroModel;
import models.VentaModel;

/**
 *
 * @author crist
 */
public class Inventario extends javax.swing.JPanel {

    //CREACION DE VARIABLES
    LibroController libroController;
    LibroModel libro;
    
    
    /**
     * Creates new form Principal
     */
    public Inventario() {
        libroController = new LibroController();        
        FlatLightLaf.install();
        initComponents();
        InitStyles();  
        LoadLibros();
        setJTexFieldChanged(this.codigoLibroConstultaTxt);
    }
    
    private void InitStyles(){
        lbl1.putClientProperty("FlatLaf.styleClass", "large");
        lbl1.setForeground(Color.black);
        lbl2.putClientProperty("FlatLaf.styleClass", "large");
        lbl2.setForeground(Color.black);
        lbl3.putClientProperty("FlatLaf.styleClass", "large");
        lbl3.setForeground(Color.black);
        lbl4.putClientProperty("FlatLaf.styleClass", "large");
        lbl4.setForeground(Color.black);
        lbl5.putClientProperty("FlatLaf.styleClass", "large");
        lbl5.setForeground(Color.black);
        lbl6.putClientProperty("FlatLaf.styleClass", "large");
        lbl6.setForeground(Color.black);
        lbl7.putClientProperty("FlatLaf.styleClass", "large");
        lbl7.setForeground(Color.black);
        lbl8.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl8.setForeground(Color.black);
        lbl9.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl9.setForeground(Color.black);
        lbl10.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl10.setForeground(Color.black);        
        lbl11.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl11.setForeground(Color.black);   
        lbl12.putClientProperty("FlatLaf.style", "font: bold $h4.regular.font");
        lbl12.setForeground(Color.black);  
        titleLbl.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        titleLbl.setForeground(Color.black);
    }

    private void LoadLibros(){
        DefaultTableModel tabla = (DefaultTableModel) librosTbl.getModel();
        tabla.setRowCount(0);
        libroController.findAll().forEach((u) -> tabla.addRow(new Object[] {u.getId(), u.getCodigo(), u.getNombre(), u.getCantidad(), u.getAutor(), u.getEditorial(), u.getPrecio()}));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        bg = new javax.swing.JPanel();
        lbl4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        codigoLibroTxt = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        librosTbl = new javax.swing.JTable();
        titleLbl = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        crearLibroBtn = new javax.swing.JButton();
        consultarLibroBtn = new javax.swing.JButton();
        nombreLibroTxt = new javax.swing.JTextField();
        editorialLibroTxt = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        autorLbl = new javax.swing.JLabel();
        editorialLbl = new javax.swing.JLabel();
        cantidadLbl = new javax.swing.JLabel();
        codigoLibroConstultaTxt = new javax.swing.JTextField();
        editarLibroBtn = new javax.swing.JButton();
        cantidadSpn = new javax.swing.JSpinner();
        eliminarLibroBtn = new javax.swing.JButton();
        lbl6 = new javax.swing.JLabel();
        precioLibroTxt = new javax.swing.JTextField();
        lbl12 = new javax.swing.JLabel();
        precioLbl = new javax.swing.JLabel();
        autorLibroTxt = new javax.swing.JTextField();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setPreferredSize(new java.awt.Dimension(715, 482));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        lbl4.setBackground(new java.awt.Color(0, 0, 0));
        lbl4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 0, 0));
        lbl4.setText("Autor:");

        lbl1.setBackground(new java.awt.Color(0, 0, 0));
        lbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Código Libro:");

        codigoLibroTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        codigoLibroTxt.setForeground(new java.awt.Color(0, 0, 0));

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Nombre Libro:");

        lbl5.setBackground(new java.awt.Color(0, 0, 0));
        lbl5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl5.setForeground(new java.awt.Color(0, 0, 0));
        lbl5.setText("Editorial:");

        librosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Codigo", "Nombre", "Cantidad", "Autor", "Editorial", "Precio"
            }
        ));
        jScrollPane1.setViewportView(librosTbl);

        titleLbl.setBackground(new java.awt.Color(0, 0, 0));
        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Consulta");

        lbl7.setBackground(new java.awt.Color(0, 0, 0));
        lbl7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl7.setForeground(new java.awt.Color(0, 0, 0));
        lbl7.setText("Código:");

        lbl8.setBackground(new java.awt.Color(0, 0, 0));
        lbl8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl8.setForeground(new java.awt.Color(0, 0, 0));
        lbl8.setText("Nombre:");

        nombreLbl.setBackground(new java.awt.Color(0, 0, 0));
        nombreLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreLbl.setForeground(new java.awt.Color(0, 0, 0));

        crearLibroBtn.setBackground(new java.awt.Color(18, 90, 173));
        crearLibroBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        crearLibroBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearLibroBtn.setText("Agregar");
        crearLibroBtn.setBorderPainted(false);
        crearLibroBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearLibroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearLibroBtnActionPerformed(evt);
            }
        });

        consultarLibroBtn.setBackground(new java.awt.Color(18, 90, 173));
        consultarLibroBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        consultarLibroBtn.setForeground(new java.awt.Color(255, 255, 255));
        consultarLibroBtn.setText("Consultar");
        consultarLibroBtn.setBorderPainted(false);
        consultarLibroBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultarLibroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarLibroBtnActionPerformed(evt);
            }
        });

        nombreLibroTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreLibroTxt.setForeground(new java.awt.Color(0, 0, 0));

        editorialLibroTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editorialLibroTxt.setForeground(new java.awt.Color(0, 0, 0));

        lbl3.setBackground(new java.awt.Color(0, 0, 0));
        lbl3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 0));
        lbl3.setText("Cantidad:");

        lbl9.setBackground(new java.awt.Color(0, 0, 0));
        lbl9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(0, 0, 0));
        lbl9.setText("Autor:");

        lbl10.setBackground(new java.awt.Color(0, 0, 0));
        lbl10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(0, 0, 0));
        lbl10.setText("Editorial");

        lbl11.setBackground(new java.awt.Color(0, 0, 0));
        lbl11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl11.setForeground(new java.awt.Color(0, 0, 0));
        lbl11.setText("Cantidad:");

        autorLbl.setBackground(new java.awt.Color(0, 0, 0));
        autorLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        autorLbl.setForeground(new java.awt.Color(0, 0, 0));

        editorialLbl.setBackground(new java.awt.Color(0, 0, 0));
        editorialLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editorialLbl.setForeground(new java.awt.Color(0, 0, 0));

        cantidadLbl.setBackground(new java.awt.Color(0, 0, 0));
        cantidadLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cantidadLbl.setForeground(new java.awt.Color(0, 0, 0));

        codigoLibroConstultaTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        codigoLibroConstultaTxt.setForeground(new java.awt.Color(0, 0, 0));

        editarLibroBtn.setBackground(new java.awt.Color(18, 90, 173));
        editarLibroBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editarLibroBtn.setForeground(new java.awt.Color(255, 255, 255));
        editarLibroBtn.setText("Editar");
        editarLibroBtn.setBorderPainted(false);
        editarLibroBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarLibroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarLibroBtnActionPerformed(evt);
            }
        });

        eliminarLibroBtn.setBackground(new java.awt.Color(18, 90, 173));
        eliminarLibroBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        eliminarLibroBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarLibroBtn.setText("Eliminar");
        eliminarLibroBtn.setBorderPainted(false);
        eliminarLibroBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarLibroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarLibroBtnActionPerformed(evt);
            }
        });

        lbl6.setBackground(new java.awt.Color(0, 0, 0));
        lbl6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(0, 0, 0));
        lbl6.setText("Precio:");

        precioLibroTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        precioLibroTxt.setForeground(new java.awt.Color(0, 0, 0));

        lbl12.setBackground(new java.awt.Color(0, 0, 0));
        lbl12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl12.setForeground(new java.awt.Color(0, 0, 0));
        lbl12.setText("Precio:");

        precioLbl.setBackground(new java.awt.Color(0, 0, 0));
        precioLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        precioLbl.setForeground(new java.awt.Color(0, 0, 0));

        autorLibroTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        autorLibroTxt.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autorLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editorialLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crearLibroBtn))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadLbl))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreLbl))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(autorLbl))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editorialLbl))
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(editarLibroBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(eliminarLibroBtn))
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addComponent(lbl7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(bgLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(consultarLibroBtn))
                                        .addComponent(codigoLibroConstultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(lbl12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precioLbl)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2)
                    .addComponent(lbl1)
                    .addComponent(nombreLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3)
                    .addComponent(cantidadSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5)
                    .addComponent(editorialLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4)
                    .addComponent(lbl6)
                    .addComponent(precioLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearLibroBtn)
                    .addComponent(autorLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(titleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl7)
                            .addComponent(codigoLibroConstultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultarLibroBtn)
                        .addGap(12, 12, 12)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl8)
                            .addComponent(nombreLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl9)
                            .addComponent(autorLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl10)
                            .addComponent(editorialLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl11)
                            .addComponent(cantidadLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl12)
                            .addComponent(precioLbl))
                        .addGap(29, 29, 29)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editarLibroBtn)
                            .addComponent(eliminarLibroBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearLibroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearLibroBtnActionPerformed
        //VALIDACION DE NULOS
        if(codigoLibroTxt.getText().equals("") || nombreLibroTxt.getText().equals("") || cantidadSpn.getValue().equals(0) || autorLibroTxt.getText().equals("") || editorialLibroTxt.getText().equals("") || precioLibroTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Complete Los Campos Necesarios");
        }else{
            //VALIDACION DE EXISTENCIA DE LIBRO
            this.libro = libroController.findByCodigo(codigoLibroTxt.getText());
            if(this.libro != null){
                JOptionPane.showMessageDialog(null, "Ya existe un libro con el codigo " + codigoLibroTxt.getText() + " \nVerifique Nuevamente");
                this.libro = null;
            }else{
                this.libro = new LibroModel(codigoLibroTxt.getText(), nombreLibroTxt.getText(), (Integer) cantidadSpn.getValue(), autorLibroTxt.getText(), editorialLibroTxt.getText(), Integer.parseInt(precioLibroTxt.getText()));
                if(libroController.create(libro)){
                    
                    JOptionPane.showMessageDialog(null, "Libro Agregado Exitosamente: \n"  + nombreLibroTxt.getText());
                    
                    codigoLibroTxt.setText("");
                    nombreLibroTxt.setText("");
                    cantidadSpn.setValue(0);
                    autorLibroTxt.setText("");
                    editorialLibroTxt.setText("");
                    precioLibroTxt.setText("");
                    
                    LoadLibros();
                    this.libro = null;
                }else{
                    JOptionPane.showMessageDialog(null, "Libro NO guardado, intente de nuevo: \n" + nombreLibroTxt.getText());
                    this.libro = null;
                }
            }
        }        
    }//GEN-LAST:event_crearLibroBtnActionPerformed

    private void consultarLibroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarLibroBtnActionPerformed
        // TODO add your handling code here:
        libro = libroController.findByCodigo(codigoLibroConstultaTxt.getText());
        if(libro != null){
            nombreLbl.setText(libro.getNombre());
            autorLbl.setText(libro.getAutor());
            editorialLbl.setText(libro.getEditorial());            
            cantidadLbl.setText(String.valueOf(libro.getCantidad()));
            precioLbl.setText( "$" + String.valueOf(libro.getPrecio()));
        }else{
            JOptionPane.showMessageDialog(null, "Libro No Existente");
            codigoLibroConstultaTxt.setText("");
            nombreLbl.setText("");
            autorLbl.setText("");
            editorialLbl.setText("");            
            cantidadLbl.setText("");
            precioLbl.setText("");
        }        
    }//GEN-LAST:event_consultarLibroBtnActionPerformed

    private void editarLibroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarLibroBtnActionPerformed
        if(libro == null){
            JOptionPane.showMessageDialog(null, "Consulte el Libro a Editar");
        }else{
            EditarInventario c = new EditarInventario(this.libro, this.librosTbl);
            c.setVisible(true);
            LoadLibros();
        }  
        codigoLibroConstultaTxt.setText("");
        nombreLbl.setText("");
        autorLbl.setText("");
        editorialLbl.setText("");            
        cantidadLbl.setText("");
        precioLbl.setText("");
    }//GEN-LAST:event_editarLibroBtnActionPerformed

    private void eliminarLibroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLibroBtnActionPerformed
        // TODO add your handling code here:
        if(libro == null){
            JOptionPane.showMessageDialog(null, "Consulte el Libro a Eliminar");
        }else{
            int confirmacion = JOptionPane.showConfirmDialog(null, "Desea eliminar el Libro:\n" + libro.getNombre());
            if(confirmacion == JOptionPane.YES_OPTION){
                if(libroController.deleteByCodigo(libro.getCodigo())){
                    JOptionPane.showMessageDialog(null, "Libro Eliminado Correctamente");                       
                }
                codigoLibroConstultaTxt.setText("");
                nombreLbl.setText("");
                autorLbl.setText("");
                editorialLbl.setText("");            
                cantidadLbl.setText("");
                precioLbl.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "El Libro No Ha Sido Eliminado");                       
            }
        }
        LoadLibros();
    }//GEN-LAST:event_eliminarLibroBtnActionPerformed
    
    //BORRAR Labels SI SE BORRA TEXTO
    private void setJTexFieldChanged(JTextField txt){
        DocumentListener documentListener = new DocumentListener() {
 
        @Override
        public void changedUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void insertUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void removeUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
        };
        txt.getDocument().addDocumentListener(documentListener);
 
    } 
    private void printIt(DocumentEvent documentEvent) {
        DocumentEvent.EventType type = documentEvent.getType();
 
        if (type.equals(DocumentEvent.EventType.CHANGE))
        {
            
        }
        else if (type.equals(DocumentEvent.EventType.INSERT))
        {
           //Método a ejecutar            
        }
        else if (type.equals(DocumentEvent.EventType.REMOVE))
        {
            //Método a ejecutar
            nombreLbl.setText("");
            autorLbl.setText("");
            editorialLbl.setText("");            
            cantidadLbl.setText("");
            precioLbl.setText("");
            this.libro = null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorLbl;
    private javax.swing.JTextField autorLibroTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cantidadLbl;
    private javax.swing.JSpinner cantidadSpn;
    private javax.swing.JTextField codigoLibroConstultaTxt;
    private javax.swing.JTextField codigoLibroTxt;
    private javax.swing.JButton consultarLibroBtn;
    private javax.swing.JButton crearLibroBtn;
    private javax.swing.JButton editarLibroBtn;
    private javax.swing.JLabel editorialLbl;
    private javax.swing.JTextField editorialLibroTxt;
    private javax.swing.JButton eliminarLibroBtn;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JTable librosTbl;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField nombreLibroTxt;
    private javax.swing.JLabel precioLbl;
    private javax.swing.JTextField precioLibroTxt;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
