/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;

/**
 *
 * @author crist
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Ventas() {
        FlatLightLaf.install();
        initComponents();
        InitStyles();  
    }
    
    private void InitStyles(){
        label4.putClientProperty("FlatLaf.styleClass", "large");
        label4.setForeground(Color.black);
        label1.putClientProperty("FlatLaf.styleClass", "large");
        label1.setForeground(Color.black);
        label2.putClientProperty("FlatLaf.styleClass", "large");
        label2.setForeground(Color.black);
        label3.putClientProperty("FlatLaf.styleClass", "large");
        label3.setForeground(Color.black);
        label5.putClientProperty("FlatLaf.styleClass", "large");
        label5.setForeground(Color.black);
        label6.putClientProperty("FlatLaf.styleClass", "large");
        label6.setForeground(Color.black);
        label7.putClientProperty("FlatLaf.styleClass", "large");
        label7.setForeground(Color.black);
        label8.putClientProperty("FlatLaf.styleClass", "large");
        label8.setForeground(Color.black);
        label9.putClientProperty("FlatLaf.styleClass", "large");
        label9.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        bg = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        librosVentasCbx = new javax.swing.JComboBox<>();
        label1 = new javax.swing.JLabel();
        idClienteVentasTxt = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        cantidadVentasSpn = new javax.swing.JSpinner();
        label6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        librosVentasTbl = new javax.swing.JTable();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        nombreClienteVentasLbl = new javax.swing.JLabel();
        ivaVentasLbl = new javax.swing.JLabel();
        totalVentasLbl = new javax.swing.JLabel();
        subtotalVentasLbl = new javax.swing.JLabel();
        membresiaVentasLbl = new javax.swing.JLabel();
        precioVentasLbl = new javax.swing.JLabel();
        agregarVentasBtn = new javax.swing.JButton();
        facturarVentasBtn = new javax.swing.JButton();
        facturarVentasBtn1 = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setPreferredSize(new java.awt.Dimension(715, 482));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        label4.setBackground(new java.awt.Color(0, 0, 0));
        label4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label4.setForeground(new java.awt.Color(0, 0, 0));
        label4.setText("Nombre Libro:");

        librosVentasCbx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        librosVentasCbx.setForeground(new java.awt.Color(0, 0, 0));
        librosVentasCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arroz", "Papa", "Carne", "Platano", "Huevos" }));
        librosVentasCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosVentasCbxActionPerformed(evt);
            }
        });

        label1.setBackground(new java.awt.Color(0, 0, 0));
        label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 0));
        label1.setText("Identificación Cliente:");

        idClienteVentasTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idClienteVentasTxt.setForeground(new java.awt.Color(0, 0, 0));
        idClienteVentasTxt.setText("jTextField1");
        idClienteVentasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteVentasTxtActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 0));
        label2.setText("Nombre Cliente:");

        label3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 0, 0));
        label3.setText("Membresía:");

        label5.setBackground(new java.awt.Color(0, 0, 0));
        label5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label5.setForeground(new java.awt.Color(0, 0, 0));
        label5.setText("Cantidad:");

        cantidadVentasSpn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        label6.setBackground(new java.awt.Color(0, 0, 0));
        label6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label6.setForeground(new java.awt.Color(0, 0, 0));
        label6.setText("Precio:");

        librosVentasTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(librosVentasTbl);

        label7.setBackground(new java.awt.Color(0, 0, 0));
        label7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label7.setForeground(new java.awt.Color(0, 0, 0));
        label7.setText("Subtotal:");

        label8.setBackground(new java.awt.Color(0, 0, 0));
        label8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label8.setForeground(new java.awt.Color(0, 0, 0));
        label8.setText("IVA:");

        label9.setBackground(new java.awt.Color(0, 0, 0));
        label9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label9.setForeground(new java.awt.Color(0, 0, 0));
        label9.setText("Total:");

        nombreClienteVentasLbl.setBackground(new java.awt.Color(0, 0, 0));
        nombreClienteVentasLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreClienteVentasLbl.setForeground(new java.awt.Color(0, 0, 0));
        nombreClienteVentasLbl.setText("{Name}");

        ivaVentasLbl.setBackground(new java.awt.Color(0, 0, 0));
        ivaVentasLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ivaVentasLbl.setForeground(new java.awt.Color(0, 0, 0));
        ivaVentasLbl.setText("$0.00");

        totalVentasLbl.setBackground(new java.awt.Color(0, 0, 0));
        totalVentasLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalVentasLbl.setForeground(new java.awt.Color(0, 0, 0));
        totalVentasLbl.setText("$0.00");

        subtotalVentasLbl.setBackground(new java.awt.Color(0, 0, 0));
        subtotalVentasLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subtotalVentasLbl.setForeground(new java.awt.Color(0, 0, 0));
        subtotalVentasLbl.setText("$0.00");

        membresiaVentasLbl.setBackground(new java.awt.Color(0, 0, 0));
        membresiaVentasLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        membresiaVentasLbl.setForeground(new java.awt.Color(0, 0, 0));
        membresiaVentasLbl.setText("{Membresia}");

        precioVentasLbl.setBackground(new java.awt.Color(0, 0, 0));
        precioVentasLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        precioVentasLbl.setForeground(new java.awt.Color(0, 0, 0));
        precioVentasLbl.setText("$0.00");

        agregarVentasBtn.setBackground(new java.awt.Color(18, 90, 173));
        agregarVentasBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        agregarVentasBtn.setForeground(new java.awt.Color(255, 255, 255));
        agregarVentasBtn.setText("Agregar");
        agregarVentasBtn.setBorderPainted(false);
        agregarVentasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarVentasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarVentasBtnActionPerformed(evt);
            }
        });

        facturarVentasBtn.setBackground(new java.awt.Color(18, 90, 173));
        facturarVentasBtn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        facturarVentasBtn.setForeground(new java.awt.Color(255, 255, 255));
        facturarVentasBtn.setText("Facturar");
        facturarVentasBtn.setBorderPainted(false);
        facturarVentasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facturarVentasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturarVentasBtnActionPerformed(evt);
            }
        });

        facturarVentasBtn1.setBackground(new java.awt.Color(18, 90, 173));
        facturarVentasBtn1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        facturarVentasBtn1.setForeground(new java.awt.Color(255, 255, 255));
        facturarVentasBtn1.setText("Generar Reporte");
        facturarVentasBtn1.setBorderPainted(false);
        facturarVentasBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facturarVentasBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturarVentasBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idClienteVentasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(label4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(librosVentasCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadVentasSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label6)))
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(precioVentasLbl)
                                .addGap(47, 47, 47)
                                .addComponent(agregarVentasBtn))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(nombreClienteVentasLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(membresiaVentasLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label7)
                                    .addComponent(label8)
                                    .addComponent(label9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalVentasLbl)
                                    .addComponent(ivaVentasLbl)
                                    .addComponent(subtotalVentasLbl)))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(facturarVentasBtn))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(facturarVentasBtn1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idClienteVentasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2)
                    .addComponent(nombreClienteVentasLbl)
                    .addComponent(membresiaVentasLbl)
                    .addComponent(label3)
                    .addComponent(label1))
                .addGap(26, 26, 26)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4)
                    .addComponent(librosVentasCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5)
                    .addComponent(cantidadVentasSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6)
                    .addComponent(precioVentasLbl)
                    .addComponent(agregarVentasBtn))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label7)
                            .addComponent(subtotalVentasLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label8)
                            .addComponent(ivaVentasLbl))
                        .addGap(12, 12, 12)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label9)
                            .addComponent(totalVentasLbl))
                        .addGap(37, 37, 37)
                        .addComponent(facturarVentasBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(facturarVentasBtn1)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void librosVentasCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosVentasCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_librosVentasCbxActionPerformed

    private void agregarVentasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarVentasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarVentasBtnActionPerformed

    private void facturarVentasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturarVentasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facturarVentasBtnActionPerformed

    private void idClienteVentasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteVentasTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteVentasTxtActionPerformed

    private void facturarVentasBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturarVentasBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facturarVentasBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarVentasBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JSpinner cantidadVentasSpn;
    private javax.swing.JButton facturarVentasBtn;
    private javax.swing.JButton facturarVentasBtn1;
    private javax.swing.JTextField idClienteVentasTxt;
    private javax.swing.JLabel ivaVentasLbl;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JComboBox<String> librosVentasCbx;
    private javax.swing.JTable librosVentasTbl;
    private javax.swing.JLabel membresiaVentasLbl;
    private javax.swing.JLabel nombreClienteVentasLbl;
    private javax.swing.JLabel precioVentasLbl;
    private javax.swing.JLabel subtotalVentasLbl;
    private javax.swing.JLabel totalVentasLbl;
    // End of variables declaration//GEN-END:variables
}
